// In: com.mea.datasync.ui
package com.mea.datasync.ui;

import javax.baja.nre.annotations.AgentOn;
import javax.baja.nre.annotations.NiagaraType;
import javax.baja.sys.Sys;
import javax.baja.sys.Type;
import javax.baja.ui.BLabel;
import javax.baja.workbench.view.BWbComponentView;

import com.mea.datasync.model.BEnhancedConnectionProfile;
import com.mea.datasync.model.BDataSourceConnection;
import com.mea.datasync.model.BTargetNiagaraStation;

/**
 * BEnhancedConnectionProfileView provides a summary view for enhanced connection profiles.
 * This view displays a professional overview of the profile configuration including
 * data source connection details, target stations, and sync status.
 */
@NiagaraType
@AgentOn(types = "datasync:EnhancedConnectionProfile")
public class BEnhancedConnectionProfileView extends BWbComponentView {

//region /*+ ------------ BEGIN BAJA AUTO GENERATED CODE ------------ +*/
//@formatter:off
/*@ $com.mea.datasync.ui.BEnhancedConnectionProfileView(2979906276)1.0$ @*/
/* Generated by Slot-o-Matic (c) Tridium, Inc. 2012-2024 */

  //region Type

  @Override
  public Type getType() { return TYPE; }
  public static final Type TYPE = Sys.loadType(BEnhancedConnectionProfileView.class);

  //endregion Type

//@formatter:on
//endregion /*+ ------------ END BAJA AUTO GENERATED CODE -------------- +*/

////////////////////////////////////////////////////////////////
// View Implementation
////////////////////////////////////////////////////////////////

  /**
   * Initialize the view and create a simple summary display.
   */
  @Override
  protected void doLoadValue(javax.baja.sys.BObject value, javax.baja.sys.Context context) throws Exception {
    super.doLoadValue(value, context);

    // Remove any existing content
    removeAll();

    // Create a simple summary label
    BLabel summaryLabel = new BLabel("<html><h2>🎉 Enhanced Connection Profile View</h2>" +
      "<p>This is a <b>custom view</b> for Enhanced Connection Profiles!</p>" +
      "<p>✅ Component-based architecture working</p>" +
      "<p>✅ Custom views registered successfully</p>" +
      "<p>✅ Clean, professional UI implementation</p>" +
      "<br><i>Profile: " + (value != null ? value.toString() : "Unknown") + "</i></html>");

    add(null, summaryLabel);

    System.out.println("✅ Enhanced Connection Profile View loaded successfully");
  }


}
